### ISSUE TITLE
500 on registration

### ISSUE THREAD

**Issue by pCyril** [aptabase/self-hosting#4]
Hello,
I just try to install on my server, all env looks good but when i try to register, i have a 500 and this error : 

`{"EventId":2001,"LogLevel":"Information","Category":"Npgsql.Command","Message":"Command execution completed (duration=8ms): SELECT id, name, email, lock_reason FROM users WHERE email = $1","State":{"Message":"Command execution completed (duration=8ms): SELECT id, name, email, lock_reason FROM users WHERE email = $1","CommandText":"SELECT id, name, email, lock_reason FROM users WHERE email = $1","DurationMs":8,"ConnectorId":30,"{OriginalFormat}":"Command execution completed (duration={DurationMs}ms): {CommandText}"}}
aptabase_app        | {"EventId":13,"LogLevel":"Error","Category":"Microsoft.AspNetCore.Server.Kestrel","Message":"Connection id \u00220HMUNV95KNDOE\u0022, Request id \u00220HMUNV95KNDOE:00000001\u0022: An unhandled exception was thrown by the application.","Exception":"System.ArgumentOutOfRangeException: IDX10720: Unable to create KeyedHashAlgorithm for algorithm \u0027HS256\u0027, the key size must be greater than: \u0027256\u0027 bits, key has \u0027240\u0027 bits. (Parameter \u0027keyBytes\u0027)    at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.ValidateKeySize(Byte[] keyBytes, String algorithm, Int32 expectedNumberOfBytes)    at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateKeyedHashAlgorithm(Byte[] keyBytes, String algorithm)    at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.CreateKeyedHashAlgorithm()    at Microsoft.IdentityModel.Tokens.DisposableObjectPool\u00601.CreateInstance()    at Microsoft.IdentityModel.Tokens.DisposableObjectPool\u00601.Allocate()    at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.GetKeyedHashAlgorithm(Byte[] keyBytes, String algorithm)    at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.Sign(Byte[] input)    at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable\u00601 notBefore, Nullable\u00601 expires, Nullable\u00601 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary\u00602 claimCollection, String tokenType, IDictionary\u00602 additionalHeaderClaims, IDictionary\u00602 additionalInnerHeaderClaims)    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)    at Aptabase.Features.Authentication.AuthTokenManager.CreateAuthToken(AuthTokenType type, String name, String email) in /work/src/Features/Authentication/AuthTokenManager.cs:line 54    at Aptabase.Features.Authentication.AuthService.SendRegisterEmailAsync(String name, String email, CancellationToken cancellationToken) in /work/src/Features/Authentication/AuthService.cs:line 76    at Aptabase.Features.Authentication.AuthController.Register(RegisterBodyRequest body, CancellationToken cancellationToken) in /work/src/Features/Authentication/AuthController.cs:line 61    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeActionMethodAsync\u003Eg__Awaited|12_0(ControllerActionInvoker invoker, ValueTask\u00601 actionResultValueTask)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeNextActionFilterAsync\u003Eg__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.\u003CInvokeInnerFilterAsync\u003Eg__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)    at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.RateLimiting.RateLimitingMiddleware.InvokeInternal(HttpContext context, EnableRateLimitingAttribute enableRateLimitingAttribute)    at ExceptionMiddleware.Invoke(HttpContext context) in /work/src/Extensions/ExceptionMiddleware.cs:line 20    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication\u00601 application)","State":{"Message":"Connection id \u00220HMUNV95KNDOE\u0022, Request id \u00220HMUNV95KNDOE:00000001\u0022: An unhandled exception was thrown by the application.","ConnectionId":"0HMUNV95KNDOE","TraceIdentifier":"0HMUNV95KNDOE:00000001","{OriginalFormat}":"Connection id \u0022{ConnectionId}\u0022, Request id \u0022{TraceIdentifier}\u0022: An unhandled exception was thrown by the application."}}
`

Thanks for your work and your help.
Cyril

**Comment by pCyril** [comment]
Ok i juste found, this was due to my AUTH_SECRET, i change it with only Alpha "CodeIgniter Encryption Keys" provided by https://randomkeygen.com/

**Comment by goenning** [comment]
Yeah the auth_secret must have at least 32 len.
