### ISSUE TITLE
[Feature] Disable registration

### ISSUE THREAD

**Issue by timokoessler** [aptabase/self-hosting#5]
It would be very convenient if you could disable the registration with an environment variable, because then an activation of SMTP for private instances would be possible and thus the login would be easier (without looking at the logs).

However, I understand that this may not has a high priority as it is primarily a SaaS product. I can also create a pull request that adds an environment variable, if that would be okay for you.

**Comment by goenning** [comment]
There's been some discussion here https://github.com/aptabase/aptabase/issues/64 so I'll close this one in favour of the other one. Someone is (or was?) going to put a PR up with an environment variable that's to only allow signup from specific emails or domains.
